CREATE DATABASE POKEMON;
USE POKEMON;
CREATE TABLE TIPO(
	idTipo INT PRIMARY KEY,
    TIPO VARCHAR(50)
);

CREATE TABLE POKEMONS(
	idPokemon INT PRIMARY KEY,
    Nombre VARCHAR(15)
);

INSERT INTO TIPO VALUES (1,'Veneno');
INSERT INTO TIPO VALUES (2,'Agua');
INSERT INTO TIPO VALUES (3,'Planta');
INSERT INTO TIPO VALUES(4,'Fuego');

INSERT INTO POKEMONS VALUES(1,'Bulbasaur');
INSERT INTO POKEMONS VALUES(2,'Charmander');
INSERT INTO POKEMONS VALUES(3,'Squirtle');
INSERT INTO POKEMONS VALUES(4,'Ekkans');
INSERT INTO POKEMONS VALUES(5,'Oddish');

SELECT *
FROM POKEMONS;

SELECT *
FROM TIPO;
