CREATE DATABASE PERSONAL;
USE PERSONAL;
CREATE TABLE DEPARTAMENTO(
	CODIGO INT PRIMARY KEY NOT NULL,NOMBRE VARCHAR(50) NOT NULL
);
CREATE TABLE EMPLEADO(
	NOMBRE VARCHAR(50) NOT NULL,
    ID INT PRIMARY KEY,
    CODIGO INT DEFAULT 1,
    FOREIGN KEY (CODIGO) REFERENCES DEPARTAMENTO(CODIGO),
    CHECK (NOMBRE!='MADRID')
);

ALTER TABLE EMPLEADO
ADD HIJOS TINYINT;

INSERT INTO DEPARTAMENTO (CODIGO,NOMBRE) VALUES (1,'Ventas');
INSERT INTO DEPARTAMENTO (CODIGO,NOMBRE) VALUES (2,'Compras');
INSERT INTO DEPARTAMENTO (CODIGO,NOMBRE) VALUES (3,'RH');

INSERT INTO EMPLEADO (ID,NOMBRE,CODIGO) VALUES (1,'Paco',1);
INSERT INTO EMPLEADO (ID,NOMBRE,CODIGO) VALUES (2,'Paco',1);
INSERT INTO EMPLEADO (ID,NOMBRE,CODIGO) VALUES (3,'Paco',2);
INSERT INTO EMPLEADO (ID,NOMBRE,CODIGO) VALUES (4,'Paco',2);
INSERT INTO EMPLEADO (ID,NOMBRE,CODIGO) VALUES (5,'Paco',3);
INSERT INTO EMPLEADO (ID,NOMBRE,CODIGO) VALUES (6,'Paco',3);

SELECT * FROM EMPLEADO;

ALTER TABLE EMPLEADO
ADD FECHAINGRESO DATE;

SELECT * FROM EMPLEADO;

/* Executing:
UPDATE `personal`.`EMPLEADO` SET `FECHAINGRESO` = '2022-05-12' WHERE (`ID` = '1');
UPDATE `personal`.`EMPLEADO` SET `FECHAINGRESO` = '2022-02-15' WHERE (`ID` = '2');
UPDATE `personal`.`EMPLEADO` SET `FECHAINGRESO` = '2021-06-20' WHERE (`ID` = '3');
UPDATE `personal`.`EMPLEADO` SET `FECHAINGRESO` = '2020-12-13' WHERE (`ID` = '4');
UPDATE `personal`.`EMPLEADO` SET `FECHAINGRESO` = '2022-01-03' WHERE (`ID` = '5');
UPDATE `personal`.`EMPLEADO` SET `FECHAINGRESO` = '2021-10-15' WHERE (`ID` = '6');

SQL script was successfully applied to the database. */

SELECT ID,NOMBRE FROM EMPLEADO WHERE CODIGO=3 ORDER BY NOMBRE;

SELECT ID,NOMBRE FROM EMPLEADO WHERE CODIGO!=3 ORDER BY NOMBRE;

SELECT ID,NOMBRE FROM EMPLEADO WHERE HIJOS<2;

SELECT * FROM EMPLEADO;

